### ISSUE TITLE
KiCad Files

### ISSUE THREAD

**Issue by eruame** [jenshackel/CubieKid#4]
Hi,

i would like to order your PCB at [aisler](https://aisler.net/) but the board manufacturer needs the board outlines. I am a total noob regarding PCB layout and editing. I tried to import the dxf/svg files into KiCad, but i cannot manage to import them as the B.Cu layer. Would you be so kind to provide the board outline also or to upload the original KiCad files, so that i can continue with this awesome project?

Thanks in advance!

**Comment by jenshackel** [comment]
Hi,
I just uploaded missing gerber files. Please try to check if it works. Feedback appreciated.
Have fun with the project.

**Comment by eruame** [comment]
Hi!
Thank you for your quick response.
Sadly, my issue is not resolved completely.
The file "CubieKidBoard_V1-3-Edge.Cuts.gbr" does not include any outlines, which [AISLER](https://aisler.net/) needs in order to cut each PCB I think.
![image](https://user-images.githubusercontent.com/43374517/48199153-85bbb300-e35b-11e8-8a5d-47e346d7ebc0.png)

Also, some PTH drill holes seem to be off compared to the copper layer.
![image](https://user-images.githubusercontent.com/43374517/48199183-a4ba4500-e35b-11e8-8180-877e39370be8.png)
![image](https://user-images.githubusercontent.com/43374517/48199370-24e0aa80-e35c-11e8-8e83-047c61f1294f.png)

Thus AISLER won't let me proceed with the purchase. Are the PTHs intentionally not placed on the pads?
![image](https://user-images.githubusercontent.com/43374517/48199545-9f112f00-e35c-11e8-8374-32fc62cdfd9b.png)
![image](https://user-images.githubusercontent.com/43374517/48199555-a89a9700-e35c-11e8-855a-6ee76f3ee1ca.png)

Thank you for spending your time to help me! =)

**Comment by jenshackel** [comment]
Hi again.
I changed the whole gerber files. The actual ones should work as they were used to produce my first batch of pcbs of revision 1.3.
Hopefully they work for you as well ;-)

**Comment by eruame** [comment]
Hi and thank you! The files are working and I can order the boards.
I have one more question regarding the IC 4001 connections.
PIN 1 is to ground. 
7 = A
6 = B
5 = NOT(AB)
4 = NOT(CD)
3 = C
2 = D

![image](https://user-images.githubusercontent.com/43374517/48260565-28d40180-e41c-11e8-8e0d-b69da44393aa.png)

You have connected NOT(CD) to B, but in the schematics NOT(CD) is connected over R7 to B. Is the schematic wrong or the PCB layout? I guess the schmeatics is wrong because normally a NAND out connects without resistors to the other input afaik.

Thank you again very much! =)

**Comment by jenshackel** [comment]
Great to hear that the gerbers work for you.
Actually it's a CD **4011**. It contains four NANDs with two inputs each. Only two are used to generate a SR flipflop.

**Comment by eruame** [comment]
Oh that was a typo, I meant this IC. Well if it works for you it will work for me. I will report back when I made progress. :-)

Am 9. November 2018 14:38:34 MEZ schrieb Jens Hackel <notifications@github.com>:

Great to hear that the gerbers work for you.
Actually it's a CD 4011. It contains four NANDs with two inputs each. Only two are used to generate a SR flipflop.

**Comment by WlfgngPrgl** [comment]
Hi, 

I'm planning to rebuilt the PCB and use a powerbank to supply the circuit. To keep the powerbank from going to sleep, it might be necessary to add a small circuit. Therefore it would be great, if you could upload the raw KiCad files to the repository. 

Many thanks for the contributions you've already made!

**Comment by jenshackel** [comment]
Hi there,
The intetion for this project ist just the other way round. This place here is not to place something for downloadung but to work on a project -together. So feel free to share your ideas, thoughts and knwoledge by placing a request. Let's improve this project for everyone!

**Comment by eruame** [comment]
Well you licensed this work as CC BY-NC-ND 4.0.
And Wolfgang wants the KiCAD files to work on them.
I'm also planning to perform some minor modifications to the CNC machine files. Do you mind a pull request if i succeed?
